baseURL = "https://wittleguys.net/"
title = "Wittle Guys"
languageCode = "en-us"

[params]
  description = "Handmade, environmentally sustainable bags, dresses and more"
  tagline = "Crafting beautiful handmade goods with pure materials and passion since 2024"
  author = "Wittle Guys"
  email = "hello@wittleguys.net"
  phone = "(555) 123-4567"
  
  [params.hero]
    title = "Handmade & Sustainable"
    subtitle = "Beautiful bags, dresses and more crafted with pure cotton and natural materials. No synthetics, only pure."
  
  [params.products]
    title = "Our Handmade Collection"
  
  [params.social]
    instagram = "#"
    facebook = "#"
    twitter = "#"
  
  [params.stripe]
    publishableKey = "***REMOVED***YOUR_STRIPE_PUBLISHABLE_KEY_HERE"

[menu]
  [[menu.main]]
    name = "Products"
    url = "/products/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

# Assets are handled by Hugo's asset pipeline

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true 
