baseURL = "https://wittleguys.net/"
title = "Wittle Guys"
theme = "tailbliss"
languageCode = "en-us"

[params]
  description = "Handcrafted wooden products with passion and precision"
  tagline = "Crafting beautiful wooden products with passion and precision since 2024"
  author = "Wittle Guys"
  email = "hello@wittleguys.net"
  phone = "(555) 123-4567"
  
  [params.hero]
    title = "Handcrafted Wooden Products"
    subtitle = "Beautiful, sustainable wooden items crafted with love and attention to detail. Each piece tells a story."
  
  [params.products]
    title = "Our Products"
  
  [params.social]
    instagram = "#"
    facebook = "#"
    twitter = "#"
  
  [params.stripe]
    publishableKey = "***REMOVED***YOUR_STRIPE_PUBLISHABLE_KEY_HERE"

[menu]
  [[menu.main]]
    name = "Products"
    url = "/products/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[params.assets]
  custom_css = ["css/main.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true 
