baseURL = "https://wittleguys.net/"
title = "wittleguys™"
languageCode = "en-us"

[params]
  environment = "live"
  description = "Handmade, environmentally sustainable bags, dresses and more"
  tagline = "Crafting beautiful handmade goods with pure materials and passion since 2024"
  author = "Wittle Guys"
  email = "support@wittleguys.net"
  phone = "(555) 123-4567"
  stripe_publishable_key = "pk_live_51RbkoIGDLGsdgzhZz6TVLb7Tiov7fw62xCP8EuYsdeVaFGbPGN9tuvlgJ8BpZcEwqYvmlpYL0bZZsuVuhxs54uMQ00m6pryPjr"
  
  [params.hero]
    title = "Handmade & Sustainable"
    subtitle = "Beautiful bags, dresses and more crafted with pure cotton and natural materials. No synthetics, only pure."
  
  [params.products]
    title = "Our Handmade Collection"
  
  [params.social]
    instagram = "#"
    facebook = "#"
    twitter = "#"
  
  [params.stripe]
    # Stripe keys are no longer stored in config.toml for security.
    # Set your publishable key as an environment variable at build time.
    testPublishableKey = ""
    livePublishableKey = ""
    publishableKey = ""

[menu]
  [[menu.main]]
    name = "Products"
    url = "/products/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Our Vision"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

# Assets are handled by Hugo's asset pipeline

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true 

# Sitemap configuration
[sitemap]
  changefreq = "weekly"
  priority = 0.5 
